=== luislerm4/xml-dtd-practica/ejercicio3/matricula.dtd
<!ELEMENT matricula (personal, pago)>
        <!ELEMENT personal (dni, nombre, titulacion, curso_academico, domicilios)>
        <!ELEMENT dni (#PCDATA)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT titulacion (#PCDATA)>
        <!ELEMENT curso_academico (#PCDATA)>
        <!ELEMENT domicilios (domicilio+)>
        <!ELEMENT domicilio (#PCDATA)>

        <!ATTLIST domicilio tipo (familiar | habitual) #REQUIRED>

        <!ELEMENT pago (tipo_matricula)>
        <!ELEMENT tipo_matricula (#PCDATA)>

=== luislerm4/xml-dtd-practica/ejercicio3/matricula.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula SYSTEM "matricula.dtd">
<matricula>
    <personal>
        <dni>12345678X</dni>
        <nombre>Angel Lerma</nombre>
        <titulacion>Ingeniería Informática</titulacion>
        <curso_academico>2025-2026</curso_academico>
        <domicilios>
            <domicilio tipo="habitual">Calle Universidad 12, Hermosillo</domicilio>
            <domicilio tipo="familiar">Av. Tecnológico 45, Hermosillo</domicilio>
        </domicilios>
    </personal>
    <pago>
        <tipo_matricula>Ordinaria</tipo_matricula>
    </pago>
</matricula>
